import '../models/models.dart';

const localEatries = [
  Eatry(
      id: 1,
      name: 'FastFoodie',
      email: 'mgt@fastfoodie.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
  Eatry(
    id: 2,
    name: 'Akif',
    email: 'mgt@akif.com',
    address: '105 rue Tchoou Ablogame Lome-Togo',
    phone: '000-888-555',
    employees: 10,
    managers: 2,
    owners: 1,
    isPromoted: false,
    isVerified: false,
  ),
  Eatry(
      id: 3,
      name: 'Ci-gusta',
      email: 'mgt@cigusta.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
  Eatry(
      id: 4,
      name: 'Ioka',
      email: 'mgt@ioka.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: false,
      isVerified: false),
  Eatry(
      id: 5,
      name: 'Golden Plate',
      email: 'mgt@golden.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
  Eatry(
      id: 6,
      name: 'Mc Donalds',
      email: 'mgt@mcdonalds.com',
      address: '105 rue Tchoou Ablogame Lome-Togo',
      phone: '000-888-555',
      employees: 10,
      managers: 2,
      owners: 1,
      isPromoted: true,
      isVerified: true),
];
